#!/usr/bin/env bash
# =============================================================================
# claude-todo-worker config for: __REPO_NAME__
# Generated by install.sh — edit freely to customize
# =============================================================================

# Virtual environment activate script (leave empty to skip)
VENV_PATH="__VENV_PATH__"

# Git branch prefix for auto-created branches
BRANCH_PREFIX="__BRANCH_PREFIX__"

# How many days to keep log files
LOG_RETENTION_DAYS=30
